'use client';

import React from 'react';
import Link from 'next/link';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#f0f9f0] flex flex-col">
      {/* Navigation */}
      <nav className="p-6">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-10 h-10 bg-[#4cbe4c] rounded-xl flex items-center justify-center shadow-soft">
              <svg 
                className="w-6 h-6 text-white" 
                fill="none" 
                stroke="currentColor" 
                viewBox="0 0 24 24"
              >
                <path 
                  strokeLinecap="round" 
                  strokeLinejoin="round" 
                  strokeWidth={2} 
                  d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" 
                />
              </svg>
            </div>
            <span className="text-xl font-semibold text-gray-800">MedReports AI</span>
          </Link>
          <Link 
            href="/" 
            className="text-gray-600 hover:text-gray-800 font-medium"
          >
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="flex-1 py-12">
        <div className="max-w-4xl mx-auto px-6">
          <div className="bg-white rounded-2xl shadow-soft-lg p-8 md:p-12">
            <h1 className="text-3xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
            
            <div className="prose prose-lg max-w-none text-gray-700 space-y-6">
              <p className="text-gray-600 mb-8">
                <strong>Last updated:</strong> {new Date().toLocaleDateString()}
              </p>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Information We Collect</h2>
                <p>We collect information you provide directly to us, including:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>Account information (email address, name) when you sign up</li>
                  <li>Medical reports and documents you upload for analysis</li>
                  <li>Analysis results and interpretations generated by our AI</li>
                  <li>Usage data and interactions with our service</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. How We Use Your Information</h2>
                <p>We use the collected information to:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>Provide and improve our medical report analysis service</li>
                  <li>Generate AI-powered interpretations of your medical reports</li>
                  <li>Maintain and secure your account</li>
                  <li>Communicate with you about our services</li>
                  <li>Comply with legal obligations</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. Data Security</h2>
                <p>We implement appropriate security measures to protect your personal and medical information:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>End-to-end encryption for data transmission</li>
                  <li>Secure storage with industry-standard protocols</li>
                  <li>Regular security audits and updates</li>
                  <li>Access controls and authentication requirements</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. Medical Data Privacy</h2>
                <p>Your medical information is treated with the highest level of confidentiality:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>Medical reports are processed securely and confidentially</li>
                  <li>We do not share your medical data with third parties without consent</li>
                  <li>Analysis results are stored securely and accessible only to you</li>
                  <li>You can request deletion of your medical data at any time</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Third-Party Services</h2>
                <p>We use trusted third-party services for:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>Authentication (Google Sign-In)</li>
                  <li>AI processing (Google Gemini AI)</li>
                  <li>Data storage and hosting</li>
                </ul>
                <p className="mt-2">These services are bound by their own privacy policies and security standards.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Your Rights</h2>
                <p>You have the right to:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>Access your personal and medical data</li>
                  <li>Request correction of inaccurate information</li>
                  <li>Request deletion of your data</li>
                  <li>Export your data in a portable format</li>
                  <li>Opt out of certain data processing activities</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Data Retention</h2>
                <p>We retain your information for as long as necessary to provide our services and comply with legal obligations. You can request deletion of your data at any time through your account settings or by contacting us.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Contact Us</h2>
                <p>If you have any questions about this Privacy Policy or our data practices, please contact us at:</p>
                <div className="bg-gray-50 p-4 rounded-lg mt-2">
                  <p className="font-medium">Email:</p>
                  <p>privacy@medreports.ai</p>
                </div>
              </section>

              <div className="border-t pt-6 mt-8">
                <p className="text-sm text-gray-500">
                  This privacy policy is effective as of the date listed above and may be updated from time to time. We will notify you of any material changes.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 