'use client';

import React from 'react';
import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#f0f9f0] flex flex-col">
      {/* Navigation */}
      <nav className="p-6">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-10 h-10 bg-[#4cbe4c] rounded-xl flex items-center justify-center shadow-soft">
              <svg 
                className="w-6 h-6 text-white" 
                fill="none" 
                stroke="currentColor" 
                viewBox="0 0 24 24"
              >
                <path 
                  strokeLinecap="round" 
                  strokeLinejoin="round" 
                  strokeWidth={2} 
                  d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" 
                />
              </svg>
            </div>
            <span className="text-xl font-semibold text-gray-800">MedReports AI</span>
          </Link>
          <Link 
            href="/" 
            className="text-gray-600 hover:text-gray-800 font-medium"
          >
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="flex-1 py-12">
        <div className="max-w-4xl mx-auto px-6">
          <div className="bg-white rounded-2xl shadow-soft-lg p-8 md:p-12">
            <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
            
            <div className="prose prose-lg max-w-none text-gray-700 space-y-6">
              <p className="text-gray-600 mb-8">
                <strong>Last updated:</strong> {new Date().toLocaleDateString()}
              </p>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
                <p>By accessing and using MedReports AI, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
                <p>MedReports AI is an AI-powered medical report analysis tool that:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>Analyzes medical reports and documents</li>
                  <li>Provides simplified explanations of medical terminology</li>
                  <li>Generates structured interpretations of test results</li>
                  <li>Offers insights about health indicators</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. User Responsibilities</h2>
                <p>As a user of our service, you agree to:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>Provide accurate and complete information</li>
                  <li>Maintain the security of your account credentials</li>
                  <li>Use the service only for lawful purposes</li>
                  <li>Not upload malicious files or content</li>
                  <li>Respect the privacy and rights of others</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. Medical and AI Disclaimer</h2>
                <div className="bg-red-50 border-l-4 border-red-500 p-4 mb-4">
                  <p className="font-semibold text-red-800">Critical Medical and AI Disclaimer</p>
                  <p className="text-red-700 mt-2">
                    <strong>All content generated by MedReports AI is AI-generated and may contain errors, inaccuracies, or misinterpretations.</strong> 
                    This service is designed to provide educational information and simplified explanations of medical reports but 
                    <strong> is not a substitute for professional medical advice, diagnosis, or treatment.</strong>
                  </p>
                </div>
                
                <h3 className="text-lg font-semibold text-gray-800 mb-3">AI-Generated Content Limitations:</h3>
                <ul className="list-disc pl-6 space-y-2 mb-4">
                  <li><strong>Artificial Intelligence Limitations:</strong> Our AI system may misinterpret medical data, miss critical information, or provide incorrect analysis</li>
                  <li><strong>No Medical Accuracy Guarantee:</strong> AI-generated interpretations may not reflect actual medical conditions or proper medical understanding</li>
                  <li><strong>Potential for Errors:</strong> Machine learning models can produce false positives, false negatives, or completely incorrect assessments</li>
                  <li><strong>Training Data Bias:</strong> AI models may reflect biases present in training data and may not account for individual medical variations</li>
                </ul>

                <h3 className="text-lg font-semibold text-gray-800 mb-3">Medical Professional Consultation Required:</h3>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Always consult with qualified healthcare professionals for medical decisions</li>
                  <li>Do not rely solely on AI-generated interpretations for any medical treatment or diagnosis</li>
                  <li>Seek immediate medical attention for urgent health concerns</li>
                  <li>Have a licensed medical professional review and interpret your actual medical reports</li>
                  <li>Our analysis is for educational and informational purposes only</li>
                  <li>This tool should be used as a supplementary resource, never as a primary medical consultation</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Service Limitations</h2>
                <p>Our service has the following limitations:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>AI analysis may not be 100% accurate</li>
                  <li>Service availability may vary based on system load</li>
                  <li>File size and format restrictions apply</li>
                  <li>Analysis results are for educational purposes only</li>
                  <li>We do not guarantee uninterrupted service</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Intellectual Property</h2>
                <p>All content, features, and functionality of MedReports AI are owned by us and are protected by international copyright, trademark, and other intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written consent.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Privacy and Data</h2>
                <p>Your privacy is important to us. Please review our <Link href="/privacy" className="text-[#4cbe4c] hover:underline">Privacy Policy</Link>, which also governs your use of the service, to understand our practices regarding the collection and use of your information.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Termination</h2>
                <p>We may terminate or suspend your account and access to our service immediately, without prior notice, for conduct that we believe violates these Terms of Service or is harmful to other users, us, or third parties.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Limitation of Liability</h2>
                <p>To the maximum extent permitted by law, MedReports AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses resulting from your use of the service.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Changes to Terms</h2>
                <p>We reserve the right to modify these terms at any time. We will notify users of any material changes by posting the new Terms of Service on this page and updating the "Last updated" date.</p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Contact Information</h2>
                <p>If you have any questions about these Terms of Service, please contact us at:</p>
                <div className="bg-gray-50 p-4 rounded-lg mt-2">
                  <p className="font-medium">Email:</p>
                  <p>legal@medreports.ai</p>
                </div>
              </section>

              <div className="border-t pt-6 mt-8">
                <p className="text-sm text-gray-500">
                  These terms of service are effective as of the date listed above. Your continued use of the service after any changes constitutes acceptance of the new terms.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 